
export const API_SEARCH_BY_NAME = `https://www.themealdb.com/api/json/v1/1/search.php?s=`;
export const API_SEARCH_BY_CHAR = 'https://www.themealdb.com/api/json/v1/1/search.php?f=a';
export const API_SEARCH_BY_ID = 'https://www.themealdb.com/api/json/v1/1/lookup.php?i=';

export const randomMeal = `https://www.themealdb.com/api/json/v1/1/random.php`
export const API_CATEGORIES = 'https://www.themealdb.com/api/json/v1/1/categories.php'
const allCategories = `https://www.themealdb.com/api/json/v1/1/list.php?c=list`;
const allareas = `https://www.themealdb.com/api/json/v1/1/list.php?a=list`;
export const API_INGREDIENTS = `https://www.themealdb.com/api/json/v1/1/list.php?i=list`;

export const API_FILTER_INGREDIENT= `https://www.themealdb.com/api/json/v1/1/filter.php?i=`
export const API_FILTER_CATEGORY = `https://www.themealdb.com/api/json/v1/1/filter.php?c=`
const filterByArea = `https://www.themealdb.com/api/json/v1/1/filter.php?a=Canadian`


/*
Add /preview to the end of the meal image URL
/images/media/meals/llcbn01574260722.jpg/small
/images/media/meals/llcbn01574260722.jpg/medium
/images/media/meals/llcbn01574260722.jpg/large

*/


// async function api(){
//     const respone = await fetch();
//     const result = await respone.json()
//     console.log(result);
// }

// api()



export const searchChar = {
  "meals": [
    {
      "idMeal": "53158",
      "strMeal": "Air fryer patatas bravas",
      "strMealAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Spanish",
      "strInstructions": "step 1\r\nSoak the potatoes in just-boiled water for 30 mins, then drain and leave to air-dry for 5 mins. Heat the air fryer to 200C. Tip the potatoes into a bowl and drizzle over 1 tbsp of the oil and add 1/2 tsp each of salt and freshly ground black pepper. Mix to coat the potatoes all over, then tip into the air fryer basket and cook for 20-30 mins until crisp and golden.\r\n\r\nstep 2\r\nMeanwhile, heat the remaining oil in a small pan over a medium-low heat and fry the onion for 8-10 mins until softened but not golden. Stir in the garlic and cook for a minute before adding the paprika and cooking for 30 seconds more. Stir in the tomato purée, cook for 1 min, then tip in the chopped tomatoes. Cook for 5-10 mins over a medium heat until thickened slightly.\r\n\r\nstep 3\r\nOnce the potatoes are cooked, tip out onto a platter and pour over the tomato sauce. Sprinkle with the basil leaves, then serve.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/3m8yae1763257951.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=kzLaw6PG2UY",
      "strIngredient1": "Potatoes",
      "strIngredient2": "Olive Oil",
      "strIngredient3": "Onion",
      "strIngredient4": "Garlic",
      "strIngredient5": "Paprika",
      "strIngredient6": "Tomato Puree",
      "strIngredient7": "Tinned Tomatos",
      "strIngredient8": "Basil Leaves",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "900g",
      "strMeasure2": "3  tablespoons",
      "strMeasure3": "1 chopped",
      "strMeasure4": "1 clove peeled crushed",
      "strMeasure5": "1 tblsp ",
      "strMeasure6": "1 tblsp ",
      "strMeasure7": "225g",
      "strMeasure8": "To serve",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/air-fryer-patatas-bravas",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-16 01:49:18"
    },
    {
      "idMeal": "53169",
      "strMeal": "Ajo blanco",
      "strMealAlternate": null,
      "strCategory": "Starter",
      "strArea": "Spanish",
      "strInstructions": "step 1\r\nTip the bread into a bowl and pour over 350ml water. Leave to soak for 10 mins.\r\n\r\nstep 2\r\nBlend the ingredients together with 350ml water and 1 tsp salt.\r\n\r\nstep 3\r\nLet the soup cool in the fridge for 1 hr or so, then serve with a drizzle of oil and some black pepper.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/5jdtie1763289302.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=AS2mSRtWyW0",
      "strIngredient1": "White bread",
      "strIngredient2": "Almonds",
      "strIngredient3": "Extra Virgin Olive Oil",
      "strIngredient4": "Garlic Clove",
      "strIngredient5": "Red Wine Vinegar",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "150g",
      "strMeasure2": "200g",
      "strMeasure3": "50 ml ",
      "strMeasure4": "1",
      "strMeasure5": "1 ½ tbsp",
      "strMeasure6": " ",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/ajo-blanco",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-16 10:32:44"
    },
    {
      "idMeal": "53138",
      "strMeal": "Alfajores",
      "strMealAlternate": null,
      "strCategory": "Dessert",
      "strArea": "Argentinian",
      "strInstructions": "Make the Dough: Cream butter and sugar. Add egg yolks and lemon zest. Gradually mix in flour and cornstarch to form a dough. Chill for 1 hour.\r\nBake the Cookies: Roll out the dough, cut into circles, and bake at 180°C (350°F) for 12-15 minutes. Let cool.\r\nAssemble: Spread dulce de leche on one cookie, then sandwich with another. Roll the edges in coconut flakes.\r\nPro Tips:\r\n\r\nChill the dough before rolling it out to make it easier to handle and to prevent the cookies from spreading too much while baking.\r\nDip the alfajores in melted chocolate and let them set on a wire rack for an extra decadent treat.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/a4kgf21763075288.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=9WR40GHpsyo",
      "strIngredient1": "All purpose flour",
      "strIngredient2": "Cornstarch",
      "strIngredient3": "Butter",
      "strIngredient4": "Sugar",
      "strIngredient5": "Egg Yolks",
      "strIngredient6": "Lemon Zest",
      "strIngredient7": "Dulce de leche",
      "strIngredient8": "Desiccated Coconut",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "300g",
      "strMeasure2": "200g",
      "strMeasure3": "200g",
      "strMeasure4": "100g ",
      "strMeasure5": "2",
      "strMeasure6": "1 teaspoon",
      "strMeasure7": " ",
      "strMeasure8": "Sprinkling",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.munchery.com/blog/the-ten-iconic-dishes-of-argentina-and-how-to-cook-them-at-home/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-13 11:32:17"
    },
    {
      "idMeal": "53111",
      "strMeal": "Anzac biscuits",
      "strMealAlternate": null,
      "strCategory": "Dessert",
      "strArea": "Australian",
      "strInstructions": "step 1\r\nHeat oven to 180C/fan 160C/gas 4. Put the oats, coconut, flour and sugar in a bowl. Melt the butter in a small pan and stir in the golden syrup. Add the bicarbonate of soda to 2 tbsp boiling water, then stir into the golden syrup and butter mixture.\r\n\r\nstep 2\r\nMake a well in the middle of the dry ingredients and pour in the butter and golden syrup mixture. Stir gently to incorporate the dry ingredients.\r\n\r\nstep 3\r\nPut dessertspoonfuls of the mixture on to buttered baking sheets, about 2.5cm/1in apart to allow room for spreading. Bake in batches for 8-10 mins until golden. Transfer to a wire rack to cool.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/q47rkb1762324620.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=1nAVbfQVWRQ",
      "strIngredient1": "Porridge oats",
      "strIngredient2": "Desiccated Coconut",
      "strIngredient3": "Plain Flour",
      "strIngredient4": "Caster Sugar",
      "strIngredient5": "Butter",
      "strIngredient6": "Golden Syrup",
      "strIngredient7": "Bicarbonate Of Soda",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "85g",
      "strMeasure2": "85g",
      "strMeasure3": "100g ",
      "strMeasure4": "100g ",
      "strMeasure5": "100g ",
      "strMeasure6": "1 tblsp ",
      "strMeasure7": "1 teaspoon",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/anzac-biscuits",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-05 04:46:03"
    },
    {
      "idMeal": "53049",
      "strMeal": "Apam balik",
      "strMealAlternate": null,
      "strCategory": "Dessert",
      "strArea": "Malaysian",
      "strInstructions": "Mix milk, oil and egg together. Sift flour, baking powder and salt into the mixture. Stir well until all ingredients are combined evenly.\r\n\r\nSpread some batter onto the pan. Spread a thin layer of batter to the side of the pan. Cover the pan for 30-60 seconds until small air bubbles appear.\r\n\r\nAdd butter, cream corn, crushed peanuts and sugar onto the pancake. Fold the pancake into half once the bottom surface is browned.\r\n\r\nCut into wedges and best eaten when it is warm.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/adxcbq1619787919.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=6R8ffRRJcrg",
      "strIngredient1": "Milk",
      "strIngredient2": "Oil",
      "strIngredient3": "Eggs",
      "strIngredient4": "Flour",
      "strIngredient5": "Baking Powder",
      "strIngredient6": "Salt",
      "strIngredient7": "Unsalted Butter",
      "strIngredient8": "Sugar",
      "strIngredient9": "Peanut Butter",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "200ml",
      "strMeasure2": "60ml",
      "strMeasure3": "2",
      "strMeasure4": "1600g",
      "strMeasure5": "3 tsp",
      "strMeasure6": "1/2 tsp",
      "strMeasure7": "25g",
      "strMeasure8": "45g",
      "strMeasure9": "3 tbs",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.nyonyacooking.com/recipes/apam-balik~SJ5WuvsDf9WQ",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52893",
      "strMeal": "Apple & Blackberry Crumble",
      "strMealAlternate": null,
      "strCategory": "Dessert",
      "strArea": "British",
      "strInstructions": "Heat oven to 190C/170C fan/gas 5. Tip the flour and sugar into a large bowl. Add the butter, then rub into the flour using your fingertips to make a light breadcrumb texture. Do not overwork it or the crumble will become heavy. Sprinkle the mixture evenly over a baking sheet and bake for 15 mins or until lightly coloured.\r\nMeanwhile, for the compote, peel, core and cut the apples into 2cm dice. Put the butter and sugar in a medium saucepan and melt together over a medium heat. Cook for 3 mins until the mixture turns to a light caramel. Stir in the apples and cook for 3 mins. Add the blackberries and cinnamon, and cook for 3 mins more. Cover, remove from the heat, then leave for 2-3 mins to continue cooking in the warmth of the pan.\r\nTo serve, spoon the warm fruit into an ovenproof gratin dish, top with the crumble mix, then reheat in the oven for 5-10 mins. Serve with vanilla ice cream.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/xvsurr1511719182.jpg",
      "strTags": "Pudding",
      "strYoutube": "https://www.youtube.com/watch?v=4vhcOwVBDO4",
      "strIngredient1": "Plain Flour",
      "strIngredient2": "Caster Sugar",
      "strIngredient3": "Butter",
      "strIngredient4": "Braeburn Apples",
      "strIngredient5": "Butter",
      "strIngredient6": "Demerara Sugar",
      "strIngredient7": "Blackberries",
      "strIngredient8": "Cinnamon",
      "strIngredient9": "Ice Cream",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "120g",
      "strMeasure2": "60g",
      "strMeasure3": "60g",
      "strMeasure4": "300g",
      "strMeasure5": "30g",
      "strMeasure6": "30g",
      "strMeasure7": "120g",
      "strMeasure8": "¼ teaspoon",
      "strMeasure9": "to serve",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": "",
      "strMeasure17": "",
      "strMeasure18": "",
      "strMeasure19": "",
      "strMeasure20": "",
      "strSource": "https://www.bbcgoodfood.com/recipes/778642/apple-and-blackberry-crumble",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "52768",
      "strMeal": "Apple Frangipan Tart",
      "strMealAlternate": null,
      "strCategory": "Dessert",
      "strArea": "British",
      "strInstructions": "Preheat the oven to 200C/180C Fan/Gas 6.\r\nPut the biscuits in a large re-sealable freezer bag and bash with a rolling pin into fine crumbs. Melt the butter in a small pan, then add the biscuit crumbs and stir until coated with butter. Tip into the tart tin and, using the back of a spoon, press over the base and sides of the tin to give an even layer. Chill in the fridge while you make the filling.\r\nCream together the butter and sugar until light and fluffy. You can do this in a food processor if you have one. Process for 2-3 minutes. Mix in the eggs, then add the ground almonds and almond extract and blend until well combined.\r\nPeel the apples, and cut thin slices of apple. Do this at the last minute to prevent the apple going brown. Arrange the slices over the biscuit base. Spread the frangipane filling evenly on top. Level the surface and sprinkle with the flaked almonds.\r\nBake for 20-25 minutes until golden-brown and set.\r\nRemove from the oven and leave to cool for 15 minutes. Remove the sides of the tin. An easy way to do this is to stand the tin on a can of beans and push down gently on the edges of the tin.\r\nTransfer the tart, with the tin base attached, to a serving plate. Serve warm with cream, crème fraiche or ice cream.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg",
      "strTags": "Tart,Baking,Fruity",
      "strYoutube": "https://www.youtube.com/watch?v=rp8Slv4INLk",
      "strIngredient1": "digestive biscuits",
      "strIngredient2": "butter",
      "strIngredient3": "Bramley apples",
      "strIngredient4": "Salted Butter",
      "strIngredient5": "caster sugar",
      "strIngredient6": "free-range eggs, beaten",
      "strIngredient7": "ground almonds",
      "strIngredient8": "almond extract",
      "strIngredient9": "flaked almonds",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "175g/6oz",
      "strMeasure2": "75g/3oz",
      "strMeasure3": "200g/7oz",
      "strMeasure4": "75g/3oz",
      "strMeasure5": "75g/3oz",
      "strMeasure6": "2",
      "strMeasure7": "75g/3oz",
      "strMeasure8": "1 tsp",
      "strMeasure9": "50g/1¾oz",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": null,
      "strMeasure17": null,
      "strMeasure18": null,
      "strMeasure19": null,
      "strMeasure20": null,
      "strSource": null,
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    },
    {
      "idMeal": "53156",
      "strMeal": "Arroz al horno (baked rice)",
      "strMealAlternate": null,
      "strCategory": "Pork",
      "strArea": "Spanish",
      "strInstructions": "step 1\r\nHeat oven to 200C/180C/gas 6. Heat half the oil in a deep frying or sauté pan (or shallow casserole dish) measuring around 30cm in diameter. Over a high heat, colour the pork belly slices on each side in several batches, then transfer to a bowl. Add the remaining oil to the pan and lower the heat to medium, then add the black pudding and bacon and fry all over for several mins. Remove with a slotted spoon. Fry the onion and peppers for around 10 mins until soft and pale gold, then add the tomato and cook until soft. Add the garlic, smoked paprika and chilli flakes and cook for another 2 mins, then put the pork, black pudding and bacon back in the pan. Add the beans, stock and whichever herb you're using, and bring everything to the boil.\r\n\r\nstep 2\r\nSprinkle the rice around the pork belly, pushing it underneath the stock. Let the stock come to the boil again, season well, then transfer to the oven (leave it uncovered). Cook for 20 mins without stirring, then check to see how the rice is doing. The rice should be tender and the stock absorbed. If it’s not ready, put back in the oven for another 5 mins, then check again. Taste for seasoning.\r\n\r\nstep 3\r\nSqueeze lemon juice over the top and drizzle over some extra virgin olive oil just before serving, if you like.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/qt4i0n1763256454.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=f-waAIrn2iA",
      "strIngredient1": "Extra Virgin Olive Oil",
      "strIngredient2": "Pork belly slices",
      "strIngredient3": "Black Pudding",
      "strIngredient4": "Bacon lardon",
      "strIngredient5": "Onion",
      "strIngredient6": "Red Pepper",
      "strIngredient7": "Plum Tomatoes",
      "strIngredient8": "Garlic Clove",
      "strIngredient9": "Paprika",
      "strIngredient10": "Chilli Flakes",
      "strIngredient11": "Dried white beans",
      "strIngredient12": "Chicken Stock",
      "strIngredient13": "Thyme",
      "strIngredient14": "Paella Rice",
      "strIngredient15": "Lemon Juice",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2 tbsp",
      "strMeasure2": "800g",
      "strMeasure3": "150g",
      "strMeasure4": "100g ",
      "strMeasure5": "1 chopped",
      "strMeasure6": "2",
      "strMeasure7": "1 chopped",
      "strMeasure8": "8",
      "strMeasure9": "4 teaspoons",
      "strMeasure10": "1/2 teaspoon",
      "strMeasure11": "200g",
      "strMeasure12": "1 1/2 L ",
      "strMeasure13": "6 parts ",
      "strMeasure14": "375g",
      "strMeasure15": "1",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/arroz-al-horno-baked-rice",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-16 01:22:48"
    },
    {
      "idMeal": "53147",
      "strMeal": "Arroz con gambas y calamar",
      "strMealAlternate": null,
      "strCategory": "Seafood",
      "strArea": "Spanish",
      "strInstructions": "step 1\r\nPeel and devein most of the prawns (a fishmonger should be able to do this for you), keeping a few whole for decoration, if you like. Heat the olive oil in a large frying pan or shallow flameproof casserole over a medium-low heat and fry the onion for 5 mins until softened. Add the bay leaf, saffron, rice and tomato purée, and cook for 1-2 mins more, stirring.\r\n\r\nstep 2\r\nPour in the wine and bubble for 1-2 mins, then pour in the seafood stock and 150ml water. Cook for 5 mins, then add the squid, season well and stir to combine. Bring to the boil, then cover and reduce the heat to a gentle simmer. Cook for 12 mins more, adding a little more water if the mixture starts to look dry.\r\n\r\nstep 3\r\nUncover the pan and stir through the peeled prawns, then arrange any whole prawns on top of the rice mixture. Cover again and simmer for a further 5-6 mins until the prawns are pink and cooked through. Leave to stand for a couple of minutes before serving from the pan.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/jc6oub1763196663.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=nFFp0ebOlOo",
      "strIngredient1": "Raw King Prawns",
      "strIngredient2": "Olive Oil",
      "strIngredient3": "Onion",
      "strIngredient4": "Bay Leaf",
      "strIngredient5": "Saffron",
      "strIngredient6": "Paella Rice",
      "strIngredient7": "Tomato Puree",
      "strIngredient8": "White Wine",
      "strIngredient9": "Seafood stock",
      "strIngredient10": "Squid",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "24",
      "strMeasure2": "2 tbsp",
      "strMeasure3": "1 small",
      "strMeasure4": "1",
      "strMeasure5": "1 pinch",
      "strMeasure6": "450g",
      "strMeasure7": "2 teaspoons",
      "strMeasure8": "200ml",
      "strMeasure9": "650ml",
      "strMeasure10": "3 Medium",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/arroz-con-gambas-y-calamar",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-15 02:00:06"
    },
    {
      "idMeal": "53133",
      "strMeal": "Asado",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "Argentinian",
      "strInstructions": "Prepare the Fire: Start a wood fire in your grill and let it burn down to coals.\r\nSeason the Meat: Generously salt the beef cuts.\r\nGrill the Meat: Place the beef on the grill, starting with the thickest cuts farthest from the coals. Add chorizo and morcilla after the beef has been cooking for a while.\r\nCook to Perfection: Cook the meat, turning occasionally, until it reaches your desired doneness. Typically, ribs may take up to 2 hours; thinner cuts will cook faster.\r\nRest and Serve: Let the meat rest for about 10 minutes before slicing. Serve with chimichurri sauce and grilled vegetables.\r\nPro Tips:\r\n\r\nUse a mix of wood and charcoal for a consistent heat source. Wood adds flavor, while charcoal maintains temperature.\r\nSeason the meat just before grilling to ensure it retains its moisture and flavor.\r\nServing Suggestions:\r\n\r\nServe with a side of chimichurri sauce, a fresh tomato salad, and crusty bread. Pair with a robust Malbec wine to complement the rich flavors of the meat.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/kgfh3q1763075438.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=q5f6Z6i1hQ8",
      "strIngredient1": "Mixed Beef Cuts",
      "strIngredient2": "Chorizo",
      "strIngredient3": "Morcilla",
      "strIngredient4": "Salt",
      "strIngredient5": "",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "2kg",
      "strMeasure2": "4",
      "strMeasure3": "2",
      "strMeasure4": "To taste",
      "strMeasure5": " ",
      "strMeasure6": " ",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.munchery.com/blog/the-ten-iconic-dishes-of-argentina-and-how-to-cook-them-at-home/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-13 10:45:01"
    },
    {
      "idMeal": "53099",
      "strMeal": "Aussie Burgers",
      "strMealAlternate": null,
      "strCategory": "Beef",
      "strArea": "Australian",
      "strInstructions": "step 1\r\nMake the burgers: Tip the meat into a bowl and sprinkle over 1 tsp salt and a good grinding of black pepper.Work with wet hands to mix in the seasoning. Divide into four with your hands and shape into burgers. (It can be frozen at this stage.)\r\n\r\nstep 2\r\nSort out your ingredients: Slice the beetroot and split the naan breads.\r\n\r\nstep 3\r\nToast the naans: Heat a griddle pan or barbecue. Griddle the naans on both sides until lightly toasted and set aside. Add the burgers to the grill or barbecue and cook for 2-3 minutes, then turn and cook the other side for a further 2-3 minutes.\r\n\r\nstep 4\r\nAssemble the dish: Set half a toasted naan on each serving plate and put a pile of rocket on each. Top with a burger, then a few slices of beetroot and a dollop of soured cream. Sprinkle with salt and freshly ground black pepper and serve immediately with a big green salad and chips. A glass of red wine wouldn’t go amiss, either.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/44bzep1761848278.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=pSupybydA_U",
      "strIngredient1": "Lean Minced Steak",
      "strIngredient2": "Cooked Beetroot",
      "strIngredient3": "Naan Bread",
      "strIngredient4": "Rocket",
      "strIngredient5": "Soured cream and chive dip",
      "strIngredient6": "",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "500g",
      "strMeasure2": "100g ",
      "strMeasure3": "2 small",
      "strMeasure4": "50g",
      "strMeasure5": "4 tablespoons",
      "strMeasure6": " ",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/aussie-burgers",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-10-30 15:03:15"
    },
    {
      "idMeal": "53127",
      "strMeal": "Authentic Norwegian Kransekake",
      "strMealAlternate": null,
      "strCategory": "Dessert",
      "strArea": "Norwegian",
      "strInstructions": "Grind almonds in an almond grinder or food processor.\r\n▢\r\nMix almonds and powdered sugar together in a large mixing bowl. Add three of the egg whites and knead the dough together with your hands until it comes together in a ball. Wrap in cling film and leave in the fridge for at least an hour, preferably until the next day.\r\n▢\r\nGrease the kransekake forms thoroughly and coat with semolina, flour, or bread crumbs.\r\n▢\r\nPreheat oven to 210°C (410°F) top and bottom heat. Divide the dough into six sections.\r\n▢\r\nSlowly add the remaining egg white to the dough and knead it until you can roll it into long sausages about as thick as your index finger. Fill the forms with the dough sausages, pinching the ends together to make rings.\r\n▢\r\nSet the forms on a baking sheet and back in the middle of the oven for about 10 – 12 minutes, until the tops are golden brown.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/yk78uc1763075719.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=fE85ioKQ7ew",
      "strIngredient1": "Almonds",
      "strIngredient2": "Egg White",
      "strIngredient3": "Powdered Sugar",
      "strIngredient4": "Powdered Sugar",
      "strIngredient5": "Egg White",
      "strIngredient6": "Lemon Juice",
      "strIngredient7": "",
      "strIngredient8": "",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3 Cups",
      "strMeasure2": "4",
      "strMeasure3": "4 cups ",
      "strMeasure4": "2 cups ",
      "strMeasure5": "1",
      "strMeasure6": "1/2 teaspoon",
      "strMeasure7": " ",
      "strMeasure8": " ",
      "strMeasure9": " ",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://scandinaviancookbook.com/classic-norwegian-kransekake-recipe/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-12 11:08:18"
    },
    {
      "idMeal": "53107",
      "strMeal": "Avocado dip with new potatoes",
      "strMealAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Australian",
      "strInstructions": "step 1\r\nWhizz half the avocado flesh with the yogurt, lime and lemon juice and seasoning. Dice the remaining avocado, then gently stir into the whizzed mix with most of the lime zest. Cover, then chill until ready to serve.\r\n\r\nstep 2\r\nBoil potatoes for 6 mins, then drain well and toss with olive oil, chilli powder and cumin seeds. Now set aside until half an hour before your guests arrive.\r\n\r\nstep 3\r\nHeat oven to 200C/180C fan/gas 6, then roast potatoes for about 30 mins, shaking the tray halfway, until golden and tender. Transfer the dip to one or two bowls, scatter with the remaining lime zest and serve with the hot potatoes, and tortilla chips for dipping.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/flrajf1762341295.jpg",
      "strTags": null,
      "strYoutube": "",
      "strIngredient1": "Avocado",
      "strIngredient2": "Natural Yoghurt",
      "strIngredient3": "Lime",
      "strIngredient4": "Lemon",
      "strIngredient5": "Baby New Potatoes",
      "strIngredient6": "Olive Oil",
      "strIngredient7": "Hot Chilli Powder",
      "strIngredient8": "Cumin Seeds",
      "strIngredient9": "Tortillas",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "3 Large",
      "strMeasure2": "200g",
      "strMeasure3": "Zest and juice of 1",
      "strMeasure4": "Juice of 1/2",
      "strMeasure5": "1.25kg",
      "strMeasure6": "2 tablespoons",
      "strMeasure7": "1 teaspoon",
      "strMeasure8": "1 teaspoon",
      "strMeasure9": "200g",
      "strMeasure10": " ",
      "strMeasure11": " ",
      "strMeasure12": " ",
      "strMeasure13": " ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "https://www.bbcgoodfood.com/recipes/avocado-citrus-dip-spicy-spuds-tortilla-chips",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": "2025-11-05 02:37:50"
    },
    {
      "idMeal": "53050",
      "strMeal": "Ayam Percik",
      "strMealAlternate": null,
      "strCategory": "Chicken",
      "strArea": "Malaysian",
      "strInstructions": "In a blender, add the ingredients for the spice paste and blend until smooth.\r\nOver medium heat, pour the spice paste in a skillet or pan and fry for 10 minutes until fragrant. Add water or oil 1 tablespoon at a time if the paste becomes too dry. Don't burn the paste. Lower the fire slightly if needed.\r\nAdd the cloves, cardamom, tamarind pulp, coconut milk, water, sugar and salt. Turn the heat up and bring the mixture to boil. Turn the heat to medium low and simmer for 10 minutes. Stir occasionally. It will reduce slightly. This is the marinade/sauce, so taste and adjust seasoning if necessary. Don't worry if it's slightly bitter. It will go away when roasting.\r\nWhen the marinade/sauce has cooled, pour everything over the chicken and marinate overnight to two days.\r\nPreheat the oven to 425 F.\r\nRemove the chicken from the marinade. Spoon the marinade onto a greased (or aluminum lined) baking sheet. Lay the chicken on top of the sauce (make sure the chicken covers the sauce and the sauce isn't exposed or it'll burn) and spread the remaining marinade on the chicken. Roast for 35-45 minutes or until internal temp of the thickest part of chicken is at least 175 F.\r\nLet chicken rest for 5 minutes. Brush the chicken with some of the oil. Serve chicken with the sauce over steamed rice (or coconut rice).",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/020z181619788503.jpg",
      "strTags": null,
      "strYoutube": "https://www.youtube.com/watch?v=9ytR28QK6I8",
      "strIngredient1": "Chicken Thighs",
      "strIngredient2": "Challots",
      "strIngredient3": "Ginger",
      "strIngredient4": "Garlic Clove",
      "strIngredient5": "Cayenne Pepper",
      "strIngredient6": "Turmeric",
      "strIngredient7": "Cumin",
      "strIngredient8": "Coriander",
      "strIngredient9": "Fennel",
      "strIngredient10": "Tamarind Paste",
      "strIngredient11": "Coconut Milk",
      "strIngredient12": "Sugar",
      "strIngredient13": "Water",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": "",
      "strIngredient17": "",
      "strIngredient18": "",
      "strIngredient19": "",
      "strIngredient20": "",
      "strMeasure1": "6",
      "strMeasure2": "16",
      "strMeasure3": "1 1/2 ",
      "strMeasure4": "6",
      "strMeasure5": "8",
      "strMeasure6": "2 tbs",
      "strMeasure7": "1 1/2 ",
      "strMeasure8": "1 1/2 ",
      "strMeasure9": "1 1/2 ",
      "strMeasure10": "2 tbs",
      "strMeasure11": "1 can ",
      "strMeasure12": "1 tsp ",
      "strMeasure13": "1 cup ",
      "strMeasure14": " ",
      "strMeasure15": " ",
      "strMeasure16": " ",
      "strMeasure17": " ",
      "strMeasure18": " ",
      "strMeasure19": " ",
      "strMeasure20": " ",
      "strSource": "http://www.curiousnut.com/roasted-spiced-chicken-ayam-percik/",
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ]
}

const searchNmae = {
  "meals": [
    {
      "idMeal": "52771",
      "strMeal": "Spicy Arrabiata Penne",
      "strMealAlternate": null,
      "strCategory": "Vegetarian",
      "strArea": "Italian",
      "strInstructions": "Bring a large pot of water to a boil. Add kosher salt to the boiling water, then add the pasta. Cook according to the package instructions, about 9 minutes.\r\nIn a large skillet over medium-high heat, add the olive oil and heat until the oil starts to shimmer. Add the garlic and cook, stirring, until fragrant, 1 to 2 minutes. Add the chopped tomatoes, red chile flakes, Italian seasoning and salt and pepper to taste. Bring to a boil and cook for 5 minutes. Remove from the heat and add the chopped basil.\r\nDrain the pasta and add it to the sauce. Garnish with Parmigiano-Reggiano flakes and more basil and serve warm.",
      "strMealThumb": "https://www.themealdb.com/images/media/meals/ustsqw1468250014.jpg",
      "strTags": "Pasta,Curry",
      "strYoutube": "https://www.youtube.com/watch?v=1IszT_guI08",
      "strIngredient1": "penne rigate",
      "strIngredient2": "olive oil",
      "strIngredient3": "garlic",
      "strIngredient4": "chopped tomatoes",
      "strIngredient5": "red chilli flakes",
      "strIngredient6": "italian seasoning",
      "strIngredient7": "basil",
      "strIngredient8": "Parmigiano-Reggiano",
      "strIngredient9": "",
      "strIngredient10": "",
      "strIngredient11": "",
      "strIngredient12": "",
      "strIngredient13": "",
      "strIngredient14": "",
      "strIngredient15": "",
      "strIngredient16": null,
      "strIngredient17": null,
      "strIngredient18": null,
      "strIngredient19": null,
      "strIngredient20": null,
      "strMeasure1": "1 pound",
      "strMeasure2": "1/4 cup",
      "strMeasure3": "3 cloves",
      "strMeasure4": "1 tin ",
      "strMeasure5": "1/2 teaspoon",
      "strMeasure6": "1/2 teaspoon",
      "strMeasure7": "6 leaves",
      "strMeasure8": "sprinkling",
      "strMeasure9": "",
      "strMeasure10": "",
      "strMeasure11": "",
      "strMeasure12": "",
      "strMeasure13": "",
      "strMeasure14": "",
      "strMeasure15": "",
      "strMeasure16": null,
      "strMeasure17": null,
      "strMeasure18": null,
      "strMeasure19": null,
      "strMeasure20": null,
      "strSource": null,
      "strImageSource": null,
      "strCreativeCommonsConfirmed": null,
      "dateModified": null
    }
  ]
}